name: Release CLI binaries

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-client:
    strategy:
      fail-fast: false
      matrix:
        lang: # from https://github.com/OpenAPITools/openapi-generator/blob/4635dda5181fd34d50643d2b9dcfcaaef64db418/docs/generators.md?plain=1#L8
        - ada
        - android
        - apex
        - bash
        - c
        - clojure
        - cpp-qt-client
        - cpp-restsdk
        - cpp-tiny
        - cpp-tizen
        - cpp-ue4
        - crystal
        - csharp
        - csharp-dotnet2
        - csharp-netcore
        - dart
        - dart-dio
        - eiffel
        - elixir
        - elm
        - erlang-client
        - erlang-proper
        - go
        - groovy
        - haskell-http-client
        - java
        - java-micronaut-client
        - javascript
        - javascript-apollo
        - javascript-closure-angular
        - javascript-flowtyped
        - jaxrs-cxf-client
        - jmeter
        - k6
        - kotlin
        - lua
        - nim
        - objc
        - ocaml
        - perl
        - php
        - php-dt
        - powershell
        - python
        - python-experimental
        - python-legacy
        - r
        - ruby
        - rust
        - scala-akka
        - scala-gatling
        - scala-httpclient-deprecated
        - scala-sttp
        - scalaz
        - swift5
        - typescript
        - typescript-angular
        - typescript-aurelia
        - typescript-axios
        - typescript-fetch
        - typescript-inversify
        - typescript-jquery
        - typescript-nestjs
        - typescript-node
        - typescript-redux-query
        - typescript-rxjs
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Generate Angular Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ${{ matrix.lang }}
          openapi-file: src/main/resources/META-INF/openapi.json
      - name: Compress folder
        run: zip -r ${{ matrix.lang }}-client.zip ${{ matrix.lang }}-client
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: cli-${{ matrix.lang }}
          path: ${{ matrix.lang }}-client.zip
          if-no-files-found: error

  release-clients:
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*/*.zip'
